# Website
baseurl:
url: http://www.example.com
lang: en

# Meta
title: Example title
description: >
  Example description
author: Author
logo: http://www.example.com/assets/img/logo.jpg
social:
  name: Author
  links:
    - https://twitter.com/page
    - https://www.facebook.com/page
    - https://www.linkedin.com/in/page/
    - https://github.com/page
twitter:
  username: author

# Contact
email: contact@example.com
email_spam: contact [at] example [dot] com

# Social
twitter_username: twitter
github_username: github
linkedin_username: linkedin

# Legal
author: Author
author_url: http://www.author.com
vendor: Vendor
vendor_url: https://www.vendor.com

# Google Analytics
google_analytics: UA-XXXXXXXX-X

# Build settings
timezone: Europe/Paris
gems:
  #- jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  #- jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
